const Discord = require("discord.js");


const Beyblade = require("./Beyblade.js");





class DemonicArmageddon extends Beyblade {


  constructor(firstOwner, id){


    super("Demonic Armageddon", "Balance", "http://pm1.narvii.com/6620/d1e927c226d49e31e18f898a617284c3e4b66704_00.jpg", "1st Form: Hell Blaze\n2nd Form: Demonic Illusion\n3rd Form: Cage of Death", firstOwner, id);


  }


  special(acted, victim, message, player){


    super.special(acted, victim, message, player);


    let move = Math.floor(Math.random() * 3);





    switch(move){


      case 0:


        let embed = new Discord.MessageEmbed()


          .setTitle(`[${acted.username}] Demonic Armageddon used **Special Move 1st Form: Hell Blaze**. 95 damage dealt.`)


          .setColor("#551a8b");


        victim.hp = victim.hp - 95;


        message.channel.send(embed);


        break;


      case 1:


        let embed2 = new Discord.MessageEmbed()


          .setTitle(`[${acted.username}] Demonic Armageddon used **Special Move 2nd Form: Demonic Illusion**. Its opponent was blinded for 1 minute and missed its attack. 65% damage reduced.`)


          .setColor("#551a8b");


        victim.atk = Math.round((victim.atk / 100) * 35);


        message.channel.send(embed2);


        break;


      case 2:


        let embed3 = new Discord.MessageEmbed()


          .setTitle(`[${acted.username}] Demonic Armageddon used **Special Move 3rd Form: Cage of Death**.  The opponent was unable to attack due to being trapped in the cage. 50 damage dealt. Gained 3 stamina from the wind pressure generated by the cage's creation.`)


          .setColor("#551a8b");


        victim.atk = 0;


        victim.hp = victim.hp - 50;


        acted.stamina = acted.stamina + 3;


        message.channel.send(embed3);


        break;


    }


  }


  displayInfo(message){


    super.displayInfo(message);


  }


}





module.exports = DemonicArmageddon;